Idp 1161 sviluppo be recesso rule engine
pagopa/idpay-reward-calculator pull request #157
Opened 2023-06-27 13:35 UTC by GiovanaSolorzano

2023-06-27 14:07 UTC, antonioT90 requested changes

2023-06-27 14:07 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/reward/controller/InstrumentApiController.java
> +@RequestMapping("/reward")
move here the more restrictive, yet general path, that could be the common prefix to each eventually added API
```suggestion
@RequestMapping("/reward/instrument")
```

2023-06-27 14:07 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/reward/service/lookup/HpanInitiativeMediatorService.java
don't re-use the Mediator! this class is a "BaseKafkaConsumer", it's wrong to use the same Service!

If you have common behavior, or try to transform these methods into public static, or create a separate Service, or create a Base abstract class to extend

2023-06-27 14:07 UTC, antonioT90 commented on src/test/java/it/gov/pagopa/reward/service/recess/InstrumentApiServiceImplTest.java
> +    InstrumentApiServiceImpl instrumentApiService;
```suggestion
    @Mock private HpanInitiativeMediatorService hpanInitiativeMediatorServiceMock;

    private InstrumentApiServiceImpl instrumentApiService;
```

2023-07-03 11:25 UTC, antonioT90 requested changes

2023-07-03 11:25 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/reward/controller/InstrumentApiController.java
> +    Mono<Void> rollbackInstruments(@PathVariable("userId") String userId,
ok, this is a rollback for the cancel operation...
But a more generic name could be "activeInstruments"

Moreove the path of the REST API is ambigous...

POST /paymentinstrument/userId/initiativeId
just by reading this, we are not able to understang what's happening...

Maybe it's better something like

PUT /paymentinstrument/userId/initiativeId/active

2023-07-05 10:18 UTC, antonioT90 requested changes

2023-07-05 10:18 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/reward/connector/repository/HpanInitiativesAtomicOpsRepositoryImpl.java
> +                                .currentDate("%s.$.%s".formatted(HpanInitiatives.Fields.onboardedInitiatives, OnboardedInitiative.Fields.updateDate)),
store as constant field names instead of let the applicatication to resolve the formatted at each invocation

2023-07-05 14:53 UTC, antonioT90 approved these changes

2023-07-06 07:56 UTC, antonioT90 requested changes

2023-07-06 07:56 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/reward/connector/repository/HpanInitiativesAtomicOpsRepository.java
> +    Mono<UpdateResult> setStatus(String userId, String initiativeId, HpanInitiativeStatus status);
let's rename into setUserInitiativeStatus

2023-07-06 07:56 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/reward/service/recess/InstrumentApiServiceImpl.java
> +    public Mono<Void> cancelInstruments(String userId, String initiativeId) {
rename into disableUserInitiativeInstruments

2023-07-06 07:56 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/reward/service/recess/InstrumentApiServiceImpl.java
> +    public Mono<Void> reactivateInstruments(String userId, String initiativeId) {
rename into enableUserInitiativeInstruments

2023-07-06 10:11 UTC, frtrinca approved these changes

2023-07-06 10:11 UTC, merged